name: assignment-test
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  full-test:
    container: cuaesd/aesd-autotest:24-assignment4-buildroot
    runs-on: self-hosted
    timeout-minutes: 120

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Dump .gitmodules content for debugging (with limited output)
        run: |
          echo "Working dir: $(pwd)"
          echo "Listing the first few files:"
          ls -1 | head -n 20  # Limit output to first 20 files in the directory
          if [ -f .gitmodules ]; then
            echo ".gitmodules contents:"
            cat .gitmodules
          else
            echo ".gitmodules file not found"
          fi

      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run full test
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
          FORCE_UNSAFE_CONFIGURE: "1"
        run: ./full-test.sh

      - name: Cleanup
        if: always()
        run: ssh-add -D

